from helpers.library_proxy import *

def algo(i):
    a = fun1(i)
    b = fun2(i)
    c = fun3(i)
    d = fun4(i)
    e = fun5(i)
    f = fun6(i)
    g = fun7(i)
    h = fun8(i)
    other_i = fun9(i)
    j = fun10(i)
    k = fun11(i)
    l = fun12(i)
    m = fun13(i)
    n = fun14(i)
    o = fun15(i)
    a1 = fun1(i)
    b1 = fun2(i)
    c1 = fun3(i)
    d1 = fun4(i)
    e1 = fun5(i)
    result = combine(i,a,b,c,d,e,f,g, h, other_i, j, k, l, m, n, o, a1,b1,c1,d1,e1)
    return result